version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      time: "06:00"
      interval: "daily"
    assignees:
      - "hexa2k9"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      time: "06:00"
      interval: "daily"
    assignees:
      - "hexa2k9"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      time: "06:00"
      interval: "daily"
    assignees:
      - "hexa2k9"
    ignore:
      - dependency-name: "yq"
